region: us-east-1

function_name: dlx-dl
handler: service.handler
description: DLX-DL Periodic Task Runner
runtime: python3.8
role: service-role/dlx-dl-role-ggxqj9bh
timeout: 315

# Build options
build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
